# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsrc/mainwindow.ui'
#
# Created: Wed May 11 15:38:25 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ueberschrift = QtWidgets.QLabel(self.centralwidget)
        self.ueberschrift.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ueberschrift.setFont(font)
        self.ueberschrift.setObjectName("ueberschrift")
        self.verticalLayout.addWidget(self.ueberschrift)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_temperatur = QtWidgets.QLabel(self.centralwidget)
        self.label_temperatur.setObjectName("label_temperatur")
        self.horizontalLayout.addWidget(self.label_temperatur)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 742, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionWasserstoff = QtWidgets.QAction(MainWindow)
        self.actionWasserstoff.setObjectName("actionWasserstoff")
        self.actionHelium = QtWidgets.QAction(MainWindow)
        self.actionHelium.setObjectName("actionHelium")
        self.actionNeon = QtWidgets.QAction(MainWindow)
        self.actionNeon.setObjectName("actionNeon")
        self.actionArgon = QtWidgets.QAction(MainWindow)
        self.actionArgon.setObjectName("actionArgon")
        self.actionKrypton = QtWidgets.QAction(MainWindow)
        self.actionKrypton.setObjectName("actionKrypton")
        self.actionXenon = QtWidgets.QAction(MainWindow)
        self.actionXenon.setObjectName("actionXenon")
        self.actionStickstoff = QtWidgets.QAction(MainWindow)
        self.actionStickstoff.setObjectName("actionStickstoff")
        self.actionAnderes_Gas = QtWidgets.QAction(MainWindow)
        self.actionAnderes_Gas.setObjectName("actionAnderes_Gas")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GasJet"))
        self.ueberschrift.setText(_translate("MainWindow", "Dichte in Partikel/cm³"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Wasserstoff"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Helium"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Neon"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Argon"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Krypton"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Xenon"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Stickstoff"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Deuterium"))
        self.label_temperatur.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionWasserstoff.setText(_translate("MainWindow", "Wasserstoff"))
        self.actionHelium.setText(_translate("MainWindow", "Helium"))
        self.actionNeon.setText(_translate("MainWindow", "Neon"))
        self.actionArgon.setText(_translate("MainWindow", "Argon"))
        self.actionKrypton.setText(_translate("MainWindow", "Krypton"))
        self.actionXenon.setText(_translate("MainWindow", "Xenon"))
        self.actionStickstoff.setText(_translate("MainWindow", "Stickstoff"))
        self.actionAnderes_Gas.setText(_translate("MainWindow", "Undefiniertes Gas"))

