# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsrc/mainwindow.ui'
#
# Created: Tue Apr 26 12:16:28 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 1, 0, 1, 1)
        self.gasart_label = QtWidgets.QLabel(self.centralwidget)
        self.gasart_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gasart_label.sizePolicy().hasHeightForWidth())
        self.gasart_label.setSizePolicy(sizePolicy)
        self.gasart_label.setMaximumSize(QtCore.QSize(16777214, 80))
        self.gasart_label.setObjectName("gasart_label")
        self.gridLayout.addWidget(self.gasart_label, 2, 0, 1, 1)
        self.ueberschrift = QtWidgets.QLabel(self.centralwidget)
        self.ueberschrift.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ueberschrift.setFont(font)
        self.ueberschrift.setObjectName("ueberschrift")
        self.gridLayout.addWidget(self.ueberschrift, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuGasart = QtWidgets.QMenu(self.menubar)
        self.menuGasart.setObjectName("menuGasart")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionWasserstoff = QtWidgets.QAction(MainWindow)
        self.actionWasserstoff.setObjectName("actionWasserstoff")
        self.actionHelium = QtWidgets.QAction(MainWindow)
        self.actionHelium.setObjectName("actionHelium")
        self.actionNeon = QtWidgets.QAction(MainWindow)
        self.actionNeon.setObjectName("actionNeon")
        self.actionArgon = QtWidgets.QAction(MainWindow)
        self.actionArgon.setObjectName("actionArgon")
        self.actionKrypton = QtWidgets.QAction(MainWindow)
        self.actionKrypton.setObjectName("actionKrypton")
        self.actionXenon = QtWidgets.QAction(MainWindow)
        self.actionXenon.setObjectName("actionXenon")
        self.actionStickstoff = QtWidgets.QAction(MainWindow)
        self.actionStickstoff.setObjectName("actionStickstoff")
        self.actionAnderes_Gas = QtWidgets.QAction(MainWindow)
        self.actionAnderes_Gas.setObjectName("actionAnderes_Gas")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuGasart.addAction(self.actionWasserstoff)
        self.menuGasart.addAction(self.actionHelium)
        self.menuGasart.addAction(self.actionNeon)
        self.menuGasart.addAction(self.actionArgon)
        self.menuGasart.addAction(self.actionKrypton)
        self.menuGasart.addAction(self.actionXenon)
        self.menuGasart.addAction(self.actionStickstoff)
        self.menuGasart.addSeparator()
        self.menuGasart.addAction(self.actionAnderes_Gas)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGasart.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gasart_label.setText(_translate("MainWindow", "Gasart"))
        self.ueberschrift.setText(_translate("MainWindow", "Dichte in Partikel/cm³"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuGasart.setTitle(_translate("MainWindow", "Gasart"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionWasserstoff.setText(_translate("MainWindow", "Wasserstoff"))
        self.actionHelium.setText(_translate("MainWindow", "Helium"))
        self.actionNeon.setText(_translate("MainWindow", "Neon"))
        self.actionArgon.setText(_translate("MainWindow", "Argon"))
        self.actionKrypton.setText(_translate("MainWindow", "Krypton"))
        self.actionXenon.setText(_translate("MainWindow", "Xenon"))
        self.actionStickstoff.setText(_translate("MainWindow", "Stickstoff"))
        self.actionAnderes_Gas.setText(_translate("MainWindow", "Undefiniertes Gas"))

